# Generated by Django 2.2.5 on 2020-01-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200120_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='id',
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
