# Generated by Django 2.2.5 on 2020-01-20 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_cart_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart_id',
            new_name='id',
        ),
    ]
