# Generated by Django 2.2.5 on 2020-01-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_remove_menu_item_cart_id'),
        ('pages', '0010_auto_20200120_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='menu_items',
            field=models.ManyToManyField(to='food.Menu_Item'),
        ),
    ]
