# Generated by Django 2.2.5 on 2020-01-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_remove_menu_item_cart_id'),
        ('pages', '0011_cart_menu_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='pizzas',
            field=models.ManyToManyField(to='food.Pizza'),
        ),
    ]
