# Generated by Django 2.2.5 on 2020-01-21 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20200121_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_item',
            name='qty',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cart_item',
            name='size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cart_item',
            name='toppings',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
