# Generated by Django 2.2.5 on 2020-01-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_order_order_items_order_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_items',
            new_name='Order_item',
        ),
        migrations.AlterField(
            model_name='order_status',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Payment Declined', 'Payment Declined'), ('Accepted', 'Accepted'), ('Preparing Food', 'Preparing Food'), ('Out For Delivery', 'Out For Delivery'), ('Completed', 'Completed')], max_length=50),
        ),
    ]
