# Generated by Django 2.2.5 on 2020-01-26 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_auto_20200126_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'get_latest_by': ['date_added']},
        ),
    ]
