# Generated by Django 2.2.5 on 2020-01-26 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_auto_20200126_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'get_latest_by': ['id']},
        ),
    ]
