# Generated by Django 2.2.5 on 2020-01-05 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='active',
        ),
        migrations.AddField(
            model_name='pizza',
            name='pizza_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.Size'),
        ),
    ]
