# Generated by Django 2.2.5 on 2020-01-17 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20200105_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sub',
            name='item_size',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='food.Size'),
        ),
    ]
