# Generated by Django 2.2.5 on 2020-01-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20200117_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='topping',
            name='amt',
            field=models.IntegerField(null=True),
        ),
    ]
