# Generated by Django 2.2.5 on 2020-01-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200120_1731'),
        ('food', '0008_auto_20200119_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_item',
            name='cart_id',
            field=models.ManyToManyField(to='pages.Cart'),
        ),
    ]
