# Generated by Django 2.2.5 on 2020-01-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_cart_user_id'),
        ('food', '0010_remove_menu_item_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_item',
            name='cart_id',
            field=models.ManyToManyField(to='pages.Cart'),
        ),
    ]
