# Generated by Django 2.2.5 on 2020-01-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_remove_menu_item_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_item',
            name='images',
            field=models.ImageField(null=True, upload_to='menu_item_photos'),
        ),
    ]
