# Generated by Django 2.2.5 on 2020-01-28 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0013_menu_item_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub',
            name='active',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='item_price',
        ),
        migrations.AddField(
            model_name='sub',
            name='category',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='food.Category'),
        ),
        migrations.AddField(
            model_name='sub',
            name='images',
            field=models.ImageField(null=True, upload_to='menu_item_photos'),
        ),
        migrations.AddField(
            model_name='sub',
            name='large_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='sub',
            name='small_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='sub',
            name='item_size',
            field=models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], max_length=50),
        ),
    ]
