# Generated by Django 2.2.5 on 2020-01-28 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0014_auto_20200128_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub',
            name='item_size',
        ),
    ]
