# Generated by Django 2.2.5 on 2020-01-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0015_remove_sub_item_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='menu_item_photos'),
        ),
        migrations.AlterField(
            model_name='sub',
            name='large_price',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='sub',
            name='small_price',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
    ]
